CREATE SCHEMA IF NOT EXISTS DEEP_POCKET;

CREATE TABLE DEEP_POCKET.ACCOUNT_TABLE(
  UUID  CHARACTER VARYING(36),
  NAME  CHARACTER VARYING(256),
  USERNAME  CHARACTER VARYING(36) UNIQUE,
  EMAIL  CHARACTER VARYING(36) UNIQUE,
  CONTACT  CHARACTER VARYING(36),
  PRIMARY KEY(UUID)
);

CREATE INDEX IDX_USERNAME ON DEEP_POCKET.ACCOUNT_TABLE(USERNAME);
CREATE INDEX IDX_EMAIL ON DEEP_POCKET.ACCOUNT_TABLE(EMAIL);

