CREATE TABLE DEEP_POCKET.NUMBER_TABLE(
  DATE_ADDED  CHARACTER VARYING(30),
  ACC_ID CHARACTER VARYING(36),
  NUMBER  CHARACTER VARYING(512),
  PAYMENT_ID CHARACTER VARYING(36),
  EDITION NUMERIC(8),
  UNIQUE (DATE_ADDED, ACC_ID, NUMBER),
  FOREIGN KEY (ACC_ID) REFERENCES DEEP_POCKET.ACCOUNT_TABLE(UUID),
  FOREIGN KEY (PAYMENT_ID) REFERENCES DEEP_POCKET.PAYMENT_INFO_TABLE(ID)
);

CREATE INDEX IDX_DATE ON DEEP_POCKET.NUMBER_TABLE(DATE_ADDED);

