CREATE TABLE DEEP_POCKET.ACCOUNT_HISTORY(
  UUID CHARACTER VARYING(36),
  ACC_ID CHARACTER VARYING(36),
  NUMBERS_PURCHASED CHARACTER VARYING(10),
  ATTEMPTS CHARACTER VARYING(10),
  PREV_WINS CHARACTER VARYING(10),
  LAST_WINNING_DATE CHARACTER VARYING(10),
  PRIMARY KEY (UUID),
  FOREIGN KEY (ACC_ID) REFERENCES DEEP_POCKET.ACCOUNT_TABLE(UUID)
);

CREATE INDEX IDX_HISTORY_ID ON DEEP_POCKET.ACCOUNT_HISTORY(ACC_ID);

