CREATE TABLE DEEP_POCKET.POTENTIAL_WINNER_TABLE(
  DATE_ADDED  CHARACTER VARYING(256),
  ACC_ID  CHARACTER VARYING(36),
  FOREIGN KEY (ACC_ID) REFERENCES DEEP_POCKET.ACCOUNT_TABLE(UUID)
);

CREATE INDEX IDX_WINNER ON DEEP_POCKET.POTENTIAL_WINNER_TABLE(DATE_ADDED, ACC_ID);
