CREATE TABLE DEEP_POCKET.PAYMENT_INFO_TABLE(
  ID  CHARACTER VARYING(36),
  ACC_ID CHARACTER VARYING(36),
  DATE_ADDED  CHARACTER VARYING(36),
  EDITION NUMERIC(8),
  PAYER_EMAIL CHARACTER VARYING(64),
  PAYER_ID CHARACTER VARYING(64),
  PAYMENT_ID CHARACTER VARYING(36),
  PAYMENT_SUCCESS CHARACTER VARYING(10),
  PURCHASED_NUMBER_COUNT CHARACTER VARYING(10),
  PRIMARY KEY(ID),
  FOREIGN KEY (ACC_ID) REFERENCES DEEP_POCKET.ACCOUNT_TABLE(UUID)
);

CREATE INDEX IDX_ACC_ID ON DEEP_POCKET.PAYMENT_INFO_TABLE(ACC_ID);