CREATE TABLE DEEP_POCKET.PREV_WINNER_INFO_TABLE(
  ACC_ID CHARACTER VARYING(36),
  PAYMENT_ID CHARACTER VARYING(36),
  WINNING_DATE CHARACTER VARYING(36),
  WINNING_NUMBER CHARACTER VARYING(10),
  EDITION NUMERIC(8)
);

